### ISSUE TITLE
The Example Output

### ISSUE THREAD

**Issue by mewmew** [mewspring/dot#1]
_From @suntong on July 2, 2016 1:21_

The [Example Output](https://godoc.org/github.com/mewspring/dot#example-Read) is now different, right? Since fix 06965e2481f46a5a90237027c2acdc90d0a7913a Print nodes before edges in Graph.String, right? 

_Copied from original issue: mewspring/dot-old#1_

**Comment by mewmew** [comment]
_From @suntong on July 2, 2016 2:26_

Confirmed. Ref:
https://github.com/suntong/lang/blob/master/lang/Go/src/graph/DotDemo1.go

**Comment by mewmew** [comment]
Hi @suntong,

You are indeed right that the output of the test cases and the example output is different from the current output of the dot library. One reason for this, as you've already pointed out, is that nodes are printed before edges (as of commit 06965e2481f46a5a90237027c2acdc90d0a7913a). Another reason is that nodes are printed in dominance order rather than alphabetical order (as of commit 52b7a3a85f4183c41b6f5ab67daaf60ca992fd00); or rather they are supposed to be, not quite sure if the current implementation is correct.

As stated in the readme, this library is a fork of @awalterschulze's [gographviz](https://github.com/awalterschulze/gographviz) package, and it was created mainly to experiment with dominator tree algorithms for control flow graphs. As a result, only a subset of graphs are considered valid graphs by the dot package, namely connected graphs. It also relies on the fact that the entry node of the graph dominates all other nodes, otherwise the dominator tree calculation panics. This is the reason for the panic reported in issue #3, which happens since [dotu.dot](https://github.com/suntong/lang/blob/master/lang/Go/src/graph/dotu.dot) contains disconnected graphs.

I appreciate that you've taken your time to report these issues. Some of them may be fixed by looking over the API, while others (namely issue #3) cannot, as it goes against the design goal of the dot package. Sorry for not having stated this with more clarity in the readme. I'll make sure to update it within the following week.

If you intend to be working with disconnected graphs, as it seems from your call graph example, I would suggest using @awalterschulze's [gographviz](https://github.com/awalterschulze/gographviz) package instead of this one. And perhaps submit a few pull requests to improve its API if you see some things lacking.

For reference, the dot package was created to support the requirements of a [decompilation pipeline](https://github.com/decomp) I've been playing around with. The dot package was (and still isn't) really intended for general use. When this changes, the work in progress notice in the readme will be removed ;)

Happy hacking and let me know if you have any other things you would wish to discuss.

Cheers /u

**Comment by mewmew** [comment]
Oh, forgot to mention one thing. When the dot package was created, gographviz was still living on code.google.com. Now that code.google.com is dead, and the official gographviz package has moved to GitHub, I've taken the liberty of creating a dedicated fork of gographviz, to further emphasize that this is a fork, and to facilitate potential pull requests in the future.

Sorry if the recreation of the repo work caused any inconveniences. To keep the issues you reported, I moved them to the new repo using https://github.com/google/github-issue-mover

**Comment by suntong** [comment]
awalterschulze's gographviz package has been dormant for ages without any updates. That's why I was super excited to see someone forked it and started working on it. Sorry I wasn't checking into the details, and didn't realize that you are going to a different direction. 

I was in fact prepared to roll up my sleeves and get involved in the "new" package with you. Is there any likelihood that we keep the dot package for general use, and derive our own "sub-class" for different purposes? As my intention was in deed to create disconnected graphs. 

Or is it a bad idea, to have totally different-purpose in one place? If so, I'll fork and work on my own...

**Comment by mewmew** [comment]
> I was in fact prepared to roll up my sleeves and get involved in the "new" package with you. Is there any likelihood that we keep the dot package for general use, and derive our own "sub-class" for different purposes? As my intention was in deed to create disconnected graphs. 

I'd definitely be interested in discussing these topics! I've created a Gitter chat room at https://gitter.im/mewspring/dot which we may use to keep the discussions in the open and let other people who are interested join.

Cheers /u

**Comment by mewmew** [comment]
@suntong For what it's worth, I've started afresh to see what the design of a DOT package would look like if making a clean break rather than patching as one go along. The intention is to keep a clear separation of concern, and ideally only handle DOT file access from the `dot` package. The specific graph data structures will be implemented independently by other packages (such as [gonum/graph](https://github.com/gonum/graph)). I intend to separate the dominator tree calculations from the general DOT and graph packages as well, and will perhaps include them in a package specifically tailored for control flow graphs.

I'd be very happy to discuss high-level designs at this point, and would welcome discussions on the requirements from an API stand-point. To keep the projects separate, I've created a new repository at https://github.com/graphism/dot. For the time being, the `mewspring/dot` project will remain as is, as it is in a functional state. In the future, hopefully the `mewspring/dot` project may be replaced by a set of generic graph packages, each focusing a on a specific aspect (such as DOT file access, graph data structures, control flow graphs and dominator calculations, etc...).

Good night /u

**Comment by mewmew** [comment]
Oh, and to discuss anything related to the clean start project, see graphism/dot#1.

**Comment by awalterschulze** [comment]
The Analyse function allows you to parse the Graph into your own structure:
```
func Analyse(graph *ast.Graph, g Interface)
```
If it implements the Interface:
```
type Interface interface {
	SetStrict(strict bool)
	SetDir(directed bool)
	SetName(name string)
	AddPortEdge(src, srcPort, dst, dstPort string, directed bool, attrs map[string]string)
	AddEdge(src, dst string, directed bool, attrs map[string]string)
	AddNode(parentGraph string, name string, attrs map[string]string)
	AddAttr(parentGraph string, field, value string)
	AddSubGraph(parentGraph string, name string, attrs map[string]string)
	String() string
}
```
That way the file parser is separate from the structure.

**Comment by mewmew** [comment]
> The Analyse function allows you to parse the Graph into your own structure.
>
> That way the file parser is separate from the structure.

@awalterschulze Thanks! I had this in the back of my mind somewhere, but seem to have forgotten since last year. I'll take a closer look and evaluate how it may be used to further separate concerns related to the dominator calculations.

Have you tried implementing support for [gonum/graph](https://github.com/gonum/graph)s? I'd be interested in knowing how feasible this would be.

**Comment by awalterschulze** [comment]
Looks like it should be pretty easy to implement those interfaces, but currently I am a little busy with an integration effort at work.

**Comment by mewmew** [comment]
This project has been superseded by https://github.com/graphism/dot, and future development will happen there.

Closing this issue for now. If it remains in the new `dot` project, open a dedicated issue for that repository.
