### ISSUE TITLE
Use official test case from Graphviz

### ISSUE THREAD

**Issue by mewmew** [mewspring/dot#2]
To stress test the lexer and parser generated from the DOT grammar, the test cases from the official Graphviz project will be downloaded and parsed.

The intention is to implement a script which downloads these test cases from the [graphviz](https://github.com/ellson/graphviz) repository, and converts them to UTF-8 encoding. To verify the read and write capabilities of the library, these test files will be parsed and the resulting graphs will be pretty-printed in DOT format and compared against the original test files, ignoring separating whitespaces.
- [x] Read support (parse test files)
- [x] Write support (pretty-print decoded graphs)
- [x] Generate PNG images from the input test DOT files and the output DOT files, and compare these images pixel by pixel.
- [x] Configure Travis to retrieve the test cases using this script

Future ambition.
- [ ] Round-trip (validate pretty-printed output vs. original input, ignoring separating spaces)

**Comment by mewmew** [comment]
The corpus of test files were parsed by the `dot` package and pretty-printed to output DOT files. These DOT files were converted to PNG images, along with the original input test files.

Using [imgcmp](https://godoc.org/github.com/mewkiz/cmd/imgcmp) the output PNG images were compared against the original PNG images generated from the input test files, which identified two images differing, namely those created from `b51.dot` and `b106.dot`.

Output PNG image created from the output DOT files generated by the `dot` package for `b51.dot`.

![dot output](https://i.imgur.com/Lf1f6Zz.png)

Original PNG image created from the input DOT test file `b51.dot`.

![orig image](https://i.imgur.com/hAVJGrJ.png)

Interestingly, the "`\n`" characters are present in the original PNG image created from the input test files, but absent from the output PNG image created from the output DOT files generated using the `dot` package. The same issue is present for the `b106.dot` file.

```
b51.png
2016/07/09 00:36:13 pixel colors differ at x=550, y=1885; c0=color.RGBA{R:0xff, G:0xfd, B:0xf1, A:0xff}, c1=color.RGBA{R:0xff, G:0xff, B:0xff, A:0xff}
```

```
b106.png
2016/07/09 00:36:18 pixel colors differ at x=5395, y=1920; c0=color.NRGBA{R:0xfe, G:0xf6, B:0xd9, A:0xff}, c1=color.NRGBA{R:0xff, G:0xff, B:0xff, A:0xff}
```

**Comment by mewmew** [comment]
The test cases are now up and running on Travis, using the original DOT test files from the Graphviz project.

**Comment by suntong** [comment]
:+1: :+1:

**Comment by suntong** [comment]
just curious, does the official DOT test files of the graphviz project cover disconnected graphs?

**Comment by mewmew** [comment]
> just curious, does the official DOT test files of the graphviz project cover disconnected graphs?

They do indeed. For an example, see `pack.dot` in the `testdata` directory, which is both disconnected and undirected :)

``` dot
graph G {
  1 -- { 2 3 4 5 6}
  2 -- { 8 9 10}
  3 -- 11 -- 12 -- 13
  a1 -- { a2 a3 a4 a5 a6}
  a2 -- { a8 a9 a10}
  A -- B
  C
}
```

![pack.png](https://i.imgur.com/dREADfp.png)

To run the test cases, do as follows.

```
cd ${GOPATH}/src/github.com/graphism/dot/testdata
make fetch
make test
```

Note, it takes approximates two minutes to run the tests, and another few to fetch the graphviz repository.
