### ISSUE TITLE
PANIC when building dominator tree and syntax error

### ISSUE THREAD

**Issue by mewmew** [mewspring/dot#3]
_From @suntong on July 2, 2016 13:45_

Please take a look at the simple code [dotu.go](https://github.com/suntong/lang/blob/master/lang/Go/src/graph/dotu.go)

It has the following problems,
- [ ] 1) It will give the "`### PANIC ### when building dominator tree for`" error during execution. 
- [ ] 2) The graph was output twice
- [x] 3) The graph will give the "`Error: syntax error in line 2 near '('`" error when processed with `dot`

This is how I run it:

```
$ go run dotu.go > /tmp/dcg-1.dot 2> /tmp/dcg-2.dot

$ cat /tmp/dcg-2.dot
2016/07/02 09:32:33 ### PANIC ### when building dominator tree for:

$ dot -Tpng /tmp/dcg-1.dot > /tmp/dcg-dn.png
Error: /tmp/dcg-1.dot: syntax error in line 2 near '('
```

I believe the third problem can be fixed if the output nodes are output in quotes. 

_Copied from original issue: mewspring/dot-old#3_

**Comment by mewmew** [comment]
> I believe the third problem can be fixed if the output nodes are output in quotes. 

I've also encountered issues with quotes being removed from the output in the past. Would love to have this issue resolved! When fixing it however, it should really be fixed upstream at the official [gographviz](https://github.com/awalterschulze/gographviz) package, and ported back to this repo.

> The graph was output twice

Not sure why this happens, if not related to the panic. Have you seen this happen for input graphs which do not produce a panic?

> It will give the "`### PANIC ### when building dominator tree for`" error during execution.

While not pretty to panic, this is intended to happen for disconnected graphs, as noted in https://github.com/mewspring/dot/issues/1#issuecomment-231176499

**Comment by mewmew** [comment]
@suntong Would you mind producing a minimal test case for the quotation issue (i.e. `syntax error in line 2 near '('`) and report it upstream to [gographviz](https://github.com/awalterschulze/gographviz)?

**Comment by suntong** [comment]
Can you send me an email at
![image](https://cloud.githubusercontent.com/assets/422244/16669308/c6e0b532-4462-11e6-96ff-cb256f207ceb.png) please? Let's talk off-line.

**Comment by suntong** [comment]
Robin, unfortunately the upstream gographviz does not have this problem. 

Take a look at the simple code [dotu0.go](https://github.com/suntong/lang/blob/master/lang/Go/src/graph/dotu0.go). How to run is at the end. 

cheers

**Comment by mewmew** [comment]
> Robin, unfortunately the upstream gographviz does not have this problem.

Interesting! Rather than unfortunate, that's great! It gives us something to work with in order to figure out what is wrong. I ran a diff between gographviz and dot and found the relevant commits which introduced the double quote issue.

Commit 4d09d16 reverts commit 03f0d86 and 08dabde, thus fixing the double quote issue. 

```shell
$ dot -Tpng /tmp/dcg-1.dot > /tmp/dcg-dn.png
```

Now produces a PNG image without any errors.

The graph is still output twice, so will need to figure out why that is the case. It also panics as the graph is disconnected, but that is the intended behaviour (at least for now, until we figure out how to turn dot into a general purpose project).

**Comment by mewmew** [comment]
This project has been superseded by https://github.com/graphism/dot, and future development will happen there.

Closing this issue for now. If it remains in the new `dot` project, open a dedicated issue for that repository.
