### ISSUE TITLE
Able to break graph apart

### ISSUE THREAD

**Issue by suntong** [mewspring/dot#7]
Hi Robin , 

Hope that when you are achieving your [Aim and Objectives](https://github.com/graphism/dot/issues/1), you will also bear in mind how the package can be used. 

One thing specific comes into my mind is the ability to break big graphs apart into smaller ones, as nowadays, any (automatically generated) chart can be super big, which makes viewing such graphs impractical. Take this [automatically generated chart](http://img.vim-cn.com/3e/8d8b82f6427ecc1c415c658cd2a962d383b181.png) for e.g., it is just too big to be comprehensible. 

Just keep a record here so that you can refer back later on when time allows. If you want to tackle it yourself, here is [a sample soure](https://gist.github.com/suntong/b4fe197e41084ca82f7862b6d56d0acc) and [how it looks](http://img.vim-cn.com/a3/c9865f9ef44f1994b760bb3c5c058c37838df0.png). Else, I'll build one myself on top of your `dot` package. 

BTW, breaking big graphs apart into smaller clusters is a hard problem. I don't have the sufficient graph theory knowledge to do it the "proper way", but I do have thought of some easy tricks that will/would make it work.

Happy hacking.

**Comment by mewmew** [comment]
Hej @suntong,

> One thing specific comes into my mind is the ability to break big graphs apart into smaller ones, as nowadays, any (automatically generated) chart can be super big, which makes viewing such graphs impractical. Take this automatically generated chart for e.g., it is just too big to be comprehensible.

This is indeed a topic I have a keen personal interest in, and have played around with quite a bit; at least within the problem domain of making sense of control flow graphs.

While I enjoy playing with this, I also have a clear intent to keep a strong separation of concern between projects. For this very reason, the `dot` package is intended to make it very easy to interact with and inter-operate between the [gonum graph representation](https://godoc.org/github.com/gonum/graph) and the DOT file format.

Specific algorithms for simplifying these graphs will then be implemented outside of the `dot` project. For instance, the concepts of [connected components](https://en.wikipedia.org/wiki/Connected_component_(graph_theory)), [communities](https://en.wikipedia.org/wiki/Community_structure), [graph isomorphisms](https://en.wikipedia.org/wiki/Graph_isomorphism), [dominators and dominance frontiers](https://en.wikipedia.org/wiki/Dominator_(graph_theory)), etc, are all very useful for getting deeper insight into the underlying components of a graph, and may help simplify larger graphs.

Following the principle of separation of concern, the `dot` project will focus on creating a solid interaction between generic graph data structures and the DOT file format. The current representation for generic graph data structures, as defined by the gonum community is the [gonum graph representation](https://godoc.org/github.com/gonum/graph). Several of these concepts have already been implemented and are supported to some extent while working with [gonum graph.Graph](https://godoc.org/github.com/gonum/graph#Graph)s. For instance:

* [Communities](https://godoc.org/github.com/gonum/graph/community)
* [Dominators](https://godoc.org/github.com/gonum/graph/path#Dominators)
* [Connected components](https://godoc.org/github.com/gonum/graph/topo#ConnectedComponents)
* [Traversal primitives](https://godoc.org/github.com/gonum/graph/traverse)
* and much more.

The key point, is that these algorithms may be implemented outside of both the `dot` project, and also outside of the `gonum/graph` project. I personally believe that key algorithms for widely known graph concepts should be contributed back to the `gonum/graph` projects, so they may be used and improved by a wider audience; while more project specific algorithms should be kept in separate repositories to keep the code base maintainable as time goes by.

I would love for the graph data structures in Go to mature over the years. For what it's worth, I'll contribute by continued experimentation and see how the `dot` project may mature and evolve into a minimal API for interacting with generic graph data structures, and converting back and forth between the DOT file format.

I hope that helped clarify some of my personal intentions with the `dot` project, and hope I have not been sending too many mixed messages in previous communication. We all learn as we go : )

Wish you all the best, and happy continued hacking in a bright new 2017!

Cheers /u

**Comment by mewmew** [comment]
@suntong The [go-callviz](https://github.com/TrueFurby/go-callvis) tool may be of interest to you, as it seems to try to solve some of the issues you've highlighted in this issue.

**Comment by suntong** [comment]
Oh thanks a lot for that!! Looks really good.

**Comment by mewmew** [comment]
Closing this issue for now, as [go-callviz](https://github.com/TrueFurby/go-callvis) and other projects may end up being better suited to solve it. Another solution is, as previously mentioned, to use the graph algorithms of the [gonum/graph](https://github.com/gonum/graph) repository to perform the analysis, which is thus a separated concern from the primary focus of this project.

P.S. @suntong Feel free to re-open this issue or add comments if you would like to continue the discussion.
